// Code generated by Slice Machine. DO NOT EDIT.

import LinkCards from './LinkCards';
import TestforTest from './TestforTest';
import Text from './Text';

export {
	LinkCards,
	TestforTest,
	Text,
};

export const components = {
	link_cards: LinkCards,
	testfor_test: TestforTest,
	text: Text,
};
