// Code generated by Slice Machine. DO NOT EDIT.

import LinkCards from './LinkCards';
import NavigationItem from './NavigationItem';
import Test from './Test';
import Text from './Text';

export {
	LinkCards,
	NavigationItem,
	Test,
	Text,
};

export const components = {
	link_cards: LinkCards,
	navigation_item: NavigationItem,
	test: Test,
	text: Text,
};
